# Setup
title:               TidyVoice2026 Challenge - Interspeech 2026
tagline:             
description:         Cross-Lingual Speaker Verification Challenge
url:                 https://tidyvoice2026.github.io
baseurl:             ''
paginate:            5
permalink:           pretty


# About/contact
author:
  name:              TidyVoice Organizers
  url:               https://github.com/tidyvoice-challenge
  email:             aref.farhadipour@uzh.ch

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
