# Setup
title:               TidyLang 2026 Challenge - Interspeech 2026
tagline:             
description:         Speaker-Controlled Language Recognition Challenge
url:                 https://tidylang2026.github.io
baseurl:             ''
paginate:            5
permalink:           pretty


# About/contact
author:
  name:              TidyLang Organizers
  url:               https://github.com/tidylang2026
  email:             aref.farhadipour@uzh.ch

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
